test_dataset_patterns: [/data/t3home000/bmaier/anomaly_presel/TTbar_*.npz, /data/t3home000/bmaier/anomaly_presel/WJets_*.npz, /data/t3home000/bmaier/anomaly_presel/WZ_*.npz]
#test_dataset_patterns: [/data/t3home000/bmaier/anomaly_presel/TTbar_*.npz, /data/t3home000/bmaier/anomaly_presel/WJets_*.npz, /data/t3home000/bmaier/anomaly_presel/WZ_*.npz, /data/t3home000/bmaier/anomaly_presel/SVJ_*.npz]
#test_dataset_patterns: [/data/t3home000/bmaier/anomaly/test_TT*.npz, /data/t3home000/bmaier/anomaly/test_WJets*.npz, /data/t3home000/bmaier/anomaly/test_WZ*.npz] 
#test_dataset_patterns: [/data/t3home000/bmaier/anomaly/test_TT*.npz, /data/t3home000/bmaier/anomaly/test_WJets*.npz] 
output: /local/anomaly/results/v4_vae/2020_04_02_23_49_36/
n_epochs: 50
n_features: 48
n_latent: 3
n_hidden: [32, 16, 8]
batch_size: 4096 
plot: /home/snarayan/public_html/figs/anomaly/v4_vae/
variational: True
