train_dataset_pattern: /data/t3home000/bmaier/anomaly/train_*.npz 
test_dataset_pattern: /data/t3home000/bmaier/anomaly/test_*.npz 
output: /local/anomaly/results/v0/
n_epochs: 50
n_features: 16
n_latent: 2
n_hidden: [12, 6]
batch_size: 4096 
lr: 0.005
lr_decay: 0.1
plot: /home/snarayan/public_html/figs/anomaly/v0/
variational: True
