train_dataset_pattern: /data/t3home000/bmaier/anomaly_presel/Big_train.npz 
test_dataset_pattern: /data/t3home000/bmaier/anomaly_presel/Big_test.npz 
output: /local/anomaly/results/v4_vae/
n_epochs: 50
n_features: 48
n_latent: 3
n_hidden: [32, 16, 8]
batch_size: 4096 
lr: 0.005
lr_decay: 0.1
plot: /home/snarayan/public_html/figs/anomaly/v4_vae/
variational: True
